# Building Node based application
language: node_js
node_js: "10.16"
sudo: required

install:
  - pip install six
  - echo no | npm ci

# Setting up the build matrix: web
matrix:
  include:
    # Running lint and unit test
    - stage: "Lint and unittest"
      cache:
        - directories:
            - $HOME/.npm
      addons:
        chrome: stable
      script:
        - echo '//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}'
        - npm run lint
        - npm run extract-scss-variables
        - npm run test:ci
        - npm run coverage-report || true

    # Running designsystem build
    - os: linux
      cache:
        - directories:
            - $HOME/.npm
      script:
        - npm run dist:designsystem
      before_deploy:
        - echo '//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}' > ~/.npmrc
      deploy:
        - provider: script
          skip_cleanup: true
          script: ./scripts/publish.js
          on:
            tags: true
            condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+

    # Release if on master and not PR
    - stage: "Release new version from master"
      if: branch = master AND type != pull_request AND commit_message !~ /Bumping version to/
      cache:
        - directories:
            - $HOME/.npm
      script: 
        - ./scripts/version_bump.sh
