apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "spa.fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "spa.name" . }}
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.hostname | quote }}
    http:
      paths:
      - backend:
          serviceName: {{ template "spa.fullname" . }}
          servicePort: web
{{- if $rootScope.Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.hostname | quote }}
    secretName: {{ template "spa.fullname" $rootScope }}
{{- end }}
